freq_range = [ 1e6, 4e9]
supply_voltage = 3.3
insertion_loss = [
	{freq = 1e6, loss = 1.3},
	{freq = 1e9, loss = 1.5},
	{freq = 2.2e9, loss = 1.8},
	{freq = 4e9, loss = 2.3},
]
iip3 = 59.0
attenuation_range = [ 0.0, 31.5 ]